// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: face.proto

package pbface2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReclusteringServiceClient is the client API for ReclusteringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReclusteringServiceClient interface {
	ReclusteringFunc(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ErrMessage, error)
}

type reclusteringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReclusteringServiceClient(cc grpc.ClientConnInterface) ReclusteringServiceClient {
	return &reclusteringServiceClient{cc}
}

func (c *reclusteringServiceClient) ReclusteringFunc(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ErrMessage, error) {
	out := new(ErrMessage)
	err := c.cc.Invoke(ctx, "/ReclusteringService/ReclusteringFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReclusteringServiceServer is the server API for ReclusteringService service.
// All implementations must embed UnimplementedReclusteringServiceServer
// for forward compatibility
type ReclusteringServiceServer interface {
	ReclusteringFunc(context.Context, *EmptyMessage) (*ErrMessage, error)
	mustEmbedUnimplementedReclusteringServiceServer()
}

// UnimplementedReclusteringServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReclusteringServiceServer struct {
}

func (UnimplementedReclusteringServiceServer) ReclusteringFunc(context.Context, *EmptyMessage) (*ErrMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReclusteringFunc not implemented")
}
func (UnimplementedReclusteringServiceServer) mustEmbedUnimplementedReclusteringServiceServer() {}

// UnsafeReclusteringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReclusteringServiceServer will
// result in compilation errors.
type UnsafeReclusteringServiceServer interface {
	mustEmbedUnimplementedReclusteringServiceServer()
}

func RegisterReclusteringServiceServer(s grpc.ServiceRegistrar, srv ReclusteringServiceServer) {
	s.RegisterService(&ReclusteringService_ServiceDesc, srv)
}

func _ReclusteringService_ReclusteringFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReclusteringServiceServer).ReclusteringFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReclusteringService/ReclusteringFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReclusteringServiceServer).ReclusteringFunc(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ReclusteringService_ServiceDesc is the grpc.ServiceDesc for ReclusteringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReclusteringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReclusteringService",
	HandlerType: (*ReclusteringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReclusteringFunc",
			Handler:    _ReclusteringService_ReclusteringFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face.proto",
}
